### ISSUE TITLE
配置完重新打开 Tik tok 后就没内容

### ISSUE THREAD

**Issue by chiupen** [Choler/TikTok#3]
用的是 Quantumlt 改了Http 复写，首次运行app可以看到影片，但再次打开时候发现没有内容。

**Comment by chiupen** [comment]
> Quantumlt要分流模式才有效

运行模式是自动分流模式，添加了证书，规则都有。首次运行 app 是可以看到日本的Tik Tok内容，就是 kill 了后重新打开就空白无内容。OS: iOS 12.1.3

**Comment by Choler** [comment]
下拉刷新下试试，应该是主机名问题 api*.tiktokv.com

**Comment by chiupen** [comment]
> 下拉刷新下试试，应该是主机名问题 api*.tiktokv.com

我再试过后还是老样子。

![img_6689](https://user-images.githubusercontent.com/34535357/52132385-fd0e9380-2679-11e9-9322-8e61bdbdba89.PNG)

我看了下 Quantumult 的请求日志

`http://mon.musical.ly/monitor/collect/?version_code=4.9.1&pass-region=1&pass-route=1&language=zh&app_name=trill&vid=17FD292A-5D29-45CB-B2F6-3BD6BC77034C&app_version=4.9.1&carrier_region=CN&is_my_cn=1&...`

请问是不是 REWRITE 没有把 CN 成功改为 JP ？

**Comment by Choler** [comment]
由于效率问题 暂不支持美区TikTok，其他区下载的可流畅播放和去水印下载，想支持美区自行添加主机名api*.musical.ly 只能兼容播放

**Comment by aniure** [comment]
我也遇到了这个问题，添加主机名 musical.ly 也不行，请问还有没有其他方法？

**Comment by pinterester** [comment]
同样的问题，首次运行成功，之后 在也打不开了。不知道是哪个环节有问题。
